bug:
  - '(?i)(bug|error|not working|wrong|incorrect|broken)'

enhancement:
  - '(?i)(feature|enhancement|add|improve|support|request|suggestion)'

question:
  - '(?i)(question|how to|what is|help|explain|why)'

documentation:
  - '(?i)(docs|documentation|readme|example|guide)'

"home assistant":
  - '(?i)(home assistant|hass|automation|homeassistant)'

configuration:
  - '(?i)(config|setup|install|yaml|options|settings|configure)'
