name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Please describe your request as clearly as possible.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the problem or need that motivates this request.
      placeholder: "As a user I want to ... so that ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you implement this?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered other solutions?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
